config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admins, path: "/admin", :controllers => {
    :sessions => 'admin/admins/sessions',
    :passwords => 'admin/admins/passwords',
  }
  
  namespace :admin do 
    get "/" => "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
  end
  
  devise_for :customers, :controllers => {
    :sessions => 'public/customers/sessions',
    :passwords => 'public/customers/passwords',
    :registrations => 'public/customers/registrations',
    :application => 'public/application'
  }

  namespace :public, path: "" do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :customers, only: [:show, :edit, :update, :destroy, :update]
    resources :items, only: [:index, :show,]
    resources :cart_items, only: [:index, :update, :destroy_item, :destroy_all, :create]
    resources :orders, only: [:new, :confirm, :thanks, :conplete, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def full_name
    Customer.first_name + Customer.last_name
  end
end

app/models/delivery.rb
class Delivery < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
end

app/models/order.rb
class Order < ApplicationRecord
end

app/controllers/admin/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admin::Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    customer = @customer
    if customer.update(customer_params)
      flash[:notice] = "Customer was successfully updated."
    redirect_to admin_customer_path
    else
    render :edit
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:first_name, :first_name_kana, :last_name, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    genre = @genre
    if genre.save
    flash[:notice] = "genre was successfully created."
    redirect_to admin_genres_path
    else
    render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    genre = @genre
    if genre.update(genre_params)
      flash[:notice] = "Genre was successfully updated."
    redirect_to admin_genres_path
    else
    render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    item = @item
    if item.save
     flash[:notice] = "item was successfully created."
    redirect_to admin_item_path(item.id)
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    item = @item
    if item.update(item_params)
      flash[:notice] = "Item was successfully updated."
    redirect_to admin_item_path(item.id)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
  end
  
  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_sign_in_path_for(resource)
  case resource
  when Admin
    admin_path
  when Customer
    public_root_path
  end
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/customers/edit.html.erb
<!-- ヘッダーの部分テンプレート -->
<%= render partial: 'admin/header_admin' %>

<div class="container">
  <div class="row">
    <%= @customer.last_name %><%= "さんの会員情報編集" %>
  </div>
  
  <div class="row">
    <div class'd-flex flex-column bd-highlight mb-3'>
      
      <%= form_with model: @customer, url:admin_customer_path, local:true do |f| %>
        <%= f.label :氏名, class: "brown-border px-3" %>
        <div class="row">
          <%= f.text_field :last_name, class: "form-control offset-1 col-4"%>
          <%= f.text_field :first_name, class: "form-control col-4"%>
        </div>
        <div class="form-group">
        <%= f.label :フリガナ, class: "brown-border px-3" %>
        <div class="row">
          <%= f.text_field :last_name_kana, class: "form-control offset-1 col-4"%>
          <%= f.text_field :first_name_kana, class: "form-control col-4"%>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :郵便番号, class: "brown-border px-3" %>
        <%= f.text_field :postal_code, class: "form-control offset-1 col-8"%>
      </div>

      <div class="form-group">
        <%= f.label :住所, class: "brown-border px-3" %>
        <%= f.text_field :address, class: "form-control offset-1 col-8"%>
      </div>

      <div class="form-group">
        <%= f.label :電話番号, class: "brown-border px-3" %>
        <%= f.text_field :telephone_number, class: "form-control offset-1 col-8"%>
      </div>

      <div class="form-group">
        <%= f.label :メールアドレス, class: "brown-border px-3" %>
        <%= f.email_field :email, class: "form-control offset-1 col-8"%>
      </div>
      
      <div class="form-group">
        <%= f.label :会員ステータス, class: "brown-border px-3" %>
        <%= f.select :is_active, [['有効',true],['退会',false]], { selected: true } %>
      </div>

      <div class="row">
        <%= f.submit "変更を保存", class: "btn btn-success offset-3 mt-3" %>
      </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<!-- ヘッダーの部分テンプレート -->
<%= render partial: 'admin/header_admin' %>

<div class='container'>
  <div class='row'>
    <h1 class=''>顧客一覧</h1>
  </div>

  <div class='row'>
    <table class="table">
      <thead>
        <tr>
          <th> 会員ID </th>
          <th> 氏名 </th>
          <th> メールアドレス </th>
          <th> ステータス </th>
        </tr>
      </thead>
      <body>
        <% @customers.each do |customer| %>
            <td>
              <%= customer.id %>
            </td>
            <td>
              <%= link_to customer.first_name, admin_customer_path(customer.id) %>
            </td>
            <td>
              <%= customer.email %>
            </td>
            <td>
              <%= customer.is_active ? "有効" : "無効" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<!-- ヘッダーの部分テンプレート -->
<%= render partial: 'admin/header_admin' %>

<div class='container'>
  <div class='row'>
    <%= @customer.last_name %><%= "さんの会員情報" %>
  </div>
  
  <div class='row'>
    <table class='table'>
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>フリガナ</th>
          <th>郵便番号</th>
          <th>住所</th>
          <th>電話番号</th>
          <th>メールアドレス</th>
          <th>会員ステータス</th>
        </tr>
      </thead>
      <tbody>
        <td><%= @customer.id %></td>
        <td><%= @customer.last_name %></td>
        <td><%= @customer.last_name_kana %></td>
        <td><%= @customer.postal_code %></td>
        <td><%= @customer.address %></td>
        <td><%= @customer.telephone_number %></td>
        <td><%= @customer.email %></td>
        <td><%= @customer.is_active ? "有効" : "退会" %></td>
      </tbody>
    </table>
  </div>
  <div class='row'>
    <div class='colmid-5 mx-auto'>
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), method: :get, class: "btn btn-info btn-sm btn-block mb-3 edit" %>
    </div>
  </div>
</div>

app/views/admin/genres/edit.html.erb
<!-- ヘッダーの部分テンプレート -->
<%= render partial: 'admin/header_admin' %>
<div class="container">
  <div class='row'>
    <h1>ジャンル編集画面</h1>
  </div>

  <div class='row'>
    <%= form_with model: @genre, url:admin_genre_path, local:true do |f| %>
    <%= f.text_field :name %>
    <%= f.submit '更新' %>
    <% end %>
  </div>
  
</div>

app/views/admin/genres/index.html.erb
  <!-- ヘッダーの部分テンプレート -->
<%= render partial: 'admin/header_admin' %>


<div class='container'>
  <div class='row'>
    <h1>ジャンル管理画面</h1>
  </div>

  <div class='row'>
    <%= form_with model: @genre, url:admin_genres_path, local:true do |f| %>
    <%= f.text_field :name %>
    <%= f.submit '新規登録' %>
    <% end %>
  </div>

  <table class='table'>
    <thead>
      <tr>
        <th>ジャンル名</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= link_to "編集", edit_admin_genre_path(genre.id) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/items/edit.html.erb
<!-- ヘッダーの部分テンプレート -->
<%= render partial: 'admin/header_admin' %>

<div class='container'>
  <div class='row'>
    <div class='col-3'>
      <div class='d-flex align-items-center justify-content-center'>
        <p>商品編集画面</p>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class'd-flex flex-column bd-highlight mb-3'>
      <%= form_with model: @item, url:admin_item_path, local:true do |f| %>
        <h4>商品画像</h4>
        <%= f.attachment_field :image %>
        
        <h4>商品名</h4>
        <%= f.text_field :name %>
        
        <h4>商品説明</h4>
        <%= f.text_area :introduction %>
        
        <h4>ジャンル</h4>
        <%= f.select :genre_id, [["ケーキ", "1"], ["ジュース", "2"]], include_blank: "選択して下さい" %>
        
        <h4>税抜価格</h4>
        <%= f.text_field :price %><p>円</p>
        
        <h4>販売ステータス</h4>
        <%= f.select :is_active, [['販売中',true],['販売停止中',false]], { selected: true } %></br>
        
        <%= f.submit "商品情報更新", :class => 'btn btn-success ' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<!-- ヘッダーの部分テンプレート -->
<%= render partial: 'admin/header_admin' %>


<div class='container'>
  
  <div class='row' >
    <h1>商品一覧</h1>
  </div>
  
  <div class='row'>
    <table class="table">
      <thead>
        <tr>
          <th> 商品ID </th>
          <th> 商品名 </th>
          <th> 税抜価格 </th>
          <th> ジャンル </th>
          <th> ステータス </th>
        </tr>
      </thead>
      <body>
        <% @items.each do |item| %>
            <td>
              <%= item.id %>
            </td>
            <td>
              <%= item.name %>
            </td>
            <td>
              <%= item.price %>
            </td>
            <td>
              <%= item.genre.name %>
            </td>
            <td>
              <%= item.is_active ? "販売中" : "販売停止中" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/items/new.html.erb
<!-- ヘッダーの部分テンプレート -->
<%= render partial: 'admin/header_admin' %>

<!-- BODY部分 -->
<div class='container'>
  <div class='row'>
    <h1></h1>
  </div>

  <div class='row'>
    <div class='col-2'>
      <p>新規商品登録</p>
    </div>
  </div>

    <!-- form_with部分 -->
  <div class='row'>
    <%= form_with model: @item, url:admin_items_path, local:true do |f| %>
      <h4>商品画像</h4>
      <%= f.attachment_field :image %>

      <h4>商品名</h4>
      <%= f.text_field :name %>

      <h4>商品説明</h4>
      <%= f.text_area :introduction %>

      <h4>ジャンル</h4>
      <%= f.collection_select :genre_id, Genre.all, :id, :name %>

      <h4>税抜価格</h4>
      <%= f.text_field :price %><p>円</p>

      <h4>販売ステータス</h4>
      <%= f.select :is_active, [["販売中",true],["販売停止中",false]], { include_blank: true, selected: 0 } %>

      <%= f.submit '新規登録' %>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<!-- ヘッダーの部分テンプレート -->
<%= render partial: 'admin/header_admin' %>

<!-- BODY部分 -->
<div class='container' >
    <div class='row' >
        <h1>商品詳細</h1>
    </div>
    <div class='row' >
        <div class='col-5 mx-auto' >
            <div class='d-flex align-items-center justify-content-center'>
                <%= attachment_image_tag @item, :image, :fill, 400, 400 %>
            </div>
            
        </div>
        <div class='col-7 '>
            <div class='d-flex flex-column bd-highlight mb-3'>
                <div class="p-2 bd-highlight"><%= @item.name %></div>
                <div class="p-2 bd-highlight"><%= @item.introduction %></div>
                <div class="p-2 bd-highlight"><%= @item.genre.name %></div>
                <div class="p-2 bd-highlight"><%= @item.price %></div>
                <div class="p-2 bd-highlight"><%= @item.is_active ? "販売中" : "販売停止中" %></div>
                <%= link_to "Edit", edit_admin_item_path(@item.id) %>
            </div>
　　　　</div>
    </div>
</div>

app/views/admin/orders/show.html.erb
<!-- ヘッダーの部分テンプレート -->
<%= render partial: 'admin/header_admin' %>

<div class="container">
  <div class="row">
    <h1 class="title">注文詳細履歴</h1>
  </div>
  <div class="row">
    <table class="table">
      <tr><th>購入者</th></tr>
      <tr><td><%= @order.name %></td></tr>
      
      <tr><th>注文日</th></tr>
      <tr><td><%= @order.created_at %></td></tr>
      
      <tr><th>配送先</th></tr>
      <tr><td><%= @order.shipping_address %></td></tr>
      
      <tr><th>支払方法</th></tr>
      <tr><td><%= @order.payment_method %></td></tr>
      
      <tr><th>注文ステータス</th></tr>
      <tr><td><%= @order.is_active %></td></tr>
      
    </table>
  </div>
</div>